
name: Formatter_INC

on:
  push:
    branches:
      - master

jobs:
  on_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out a repo
      uses: actions/checkout@v2
    
    - name: Make builds
      run : |
        mkdir cmake-build && cd cmake-build
        cmake ..
        make
    - name: Run hello_world_application
      run : |
        cd cmake-build/hello_world_application
        ./hello_world
    - name: First attempt to run solver_application
      run : | 
        cd cmake-build/solver_application
        ./solver 1 2 1
    - name: Second attempt to run solver_application
      run : | 
        cd cmake-build/solver_application
        ./solver 21 16 9
